sudo: required
services:
    - docker

before install:
    - docker build -t thirumalpalwai/docker-react -f Dockerfile.dev .

script:
    - docker run -it -e CI=true thirumalpalwai/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "nokiadocker"
    env: "Nokiadocker-env-1"
    bucket_name: "elasticbeanstalk-us-east-2-411318328549"
    bucket_path: "nokiadocker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY