sudo: required
services:
    - docker

before install:
    - docker build -t thirumalpalwai/docker-react -f Dockerfile.dev .

scrip:
    - docker run -e CI=true thirumalpalwai/docker-react npm run test